### ISSUE TITLE
Baseline and competition status

### ISSUE THREAD

**Issue by MrRobot2211** [iglu-contest/iglu-2022-rl-baseline#9]
Hi is this baseline still a WIP or can we use it?
Has the competition started?

**Comment by artemZholus** [comment]
Hi, yes, the baseline is in the WIP status. We will finalize it in a few days. Please, stay tuned to the competition website: https://www.aicrowd.com/challenges/neurips-2022-iglu-challenge
The competition has started a few days ago.
